githubRepoOwner: marcosfelt
githubRepoName: chao_fan
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: true
requireApproval: false
mergeMethod: merge
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
