name: Update Recipe DB

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    update_db:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"

        - name: Install Python package
          run: pip install .

        - name: Update Recipe DB
          env:
            PINTEREST_EMAIL: ${{ secrets.PINTEREST_EMAIL }}
            PINTEREST_PASSWORD: ${{ secrets.PINTEREST_PASSWORD }}
            PINTEREST_USERNAME: ${{ secrets.PINTEREST_USERNAME }}
            SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
          run: python chao_fan/pipelines/update_recipe_db.py

        - name: Commit changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add database.db
            git commit -m "Update recipe database"